storage_account: tfci
container: tf-ci-state
terraform_location: /usr/bin/terraform
tf_prefix: tf-
resource_group_name: tf-test-full-setup
default_resource_group_name: tf-default-full-setup
backend: false
